data:
  train_files: FSCDC/ReasonMap-Train
  val_files: None
  prompt_key: question
  max_prompt_length: 20000
  max_response_length: 2048
  rollout_batch_size: 16
  shuffle: true
  seed: 42
  max_pixels: 128450560
  min_pixels: 3136

algorithm:
  adv_estimator: grpo
  kl_coef: 0.0

worker:
  actor:
    global_batch_size: 16
    micro_batch_size_per_device_for_update: 16
    micro_batch_size_per_device_for_experience: 16
    max_grad_norm: 1.0
    use_kl_loss: true
    kl_loss_coef: 5.0e-3
    kl_loss_type: low_var_kl
    model:
      model_path: path/to/sft_trained_model 
      enable_gradient_checkpointing: true
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
    fsdp:
      param_offload: false
      optimizer_offload: false
      torch_dtype: null
    offload:
      param_offload: true
      optimizer_offload: true

  rollout:
    temperature: 1.0
    tensor_parallel_size: 2
    gpu_memory_utilization: 0.6
    n: 8
    enable_chunked_prefill: true

  ref:
    offload:
      param_offload: true

  reward:
    reward_type: function
    compute_score: reason_map

trainer:
  total_episodes: 1
  logger: ["console"]
  project_name: reason_map
  n_gpus_per_node: 8
  nnodes: 1
  save_freq: 100
  test_freq: 100000
  val_before_train: false
  val_only: false

utils:
  